# Generated by Django 4.2 on 2023-12-09 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_group_remove_person_address_person_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='places',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='group',
            name='swipes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
