# Generated by Django 4.2 on 2023-12-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_group_places_alter_group_swipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, default='Group', max_length=200, null=True),
        ),
    ]
