# Generated by Django 4.2 on 2023-12-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='places',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='swipes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
