# Generated by Django 4.2 on 2023-12-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_group_places_alter_group_swipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='places',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='swipes',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
