# Generated by Django 4.2 on 2023-12-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_group_places_alter_group_swipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='places',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='swipes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
