# Generated by Django 5.0 on 2024-01-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
