# Generated by Django 5.0 on 2024-01-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_person_longitude_person_places_person_swipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='address',
        ),
        migrations.AddField(
            model_name='group',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
