# Generated by Django 5.0 on 2024-01-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_group_address_group_latitude_group_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=7),
        ),
        migrations.AlterField(
            model_name='group',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=7),
        ),
    ]
