# Generated by Django 4.2.9 on 2024-01-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_person_radius_alter_group_radius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='group',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='use_address',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
